version: "3.9"

services:
  api:
    container_name: api-camon
    image: api-camon
    networks:
      - camon
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  media:
    container_name: media-camon
    image: media-camon
    networks:
      - camon
    ports:
      - "3001:3001"
      - "30000-31000:30000-31000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_MEDIA=${REDIS_MEDIA}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_SERVER_URL=${API_SERVER_URL}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - RECORD_SERVER_URL=${RECORD_SERVER_URL}
      - SERVER_PRIVATE_IP=${SERVER_PRIVATE_IP}
      - PUBLIC_RECORD_SERVER_URL=${PUBLIC_RECORD_SERVER_URL}

  chat:
    container_name: chat-camon
    image: chat-camon
    networks:
      - camon
    ports:
      - "3002:3002"
    environment:
      - CHAT_PORT=${CHAT_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHAT=${REDIS_CHAT}
      - JWT_SECRET=${JWT_SECRET}

  record:
    container_name: record-camon
    image: record-camon
    networks:
      camon:
        ipv4_address: 172.19.0.10
    expose:
        - "3003"
    ports:
      - "3003:3003"
    environment:
      - NCLOUD_ACCESS_KEY=${NCLOUD_ACCESS_KEY}
      - NCLOUD_SECRET_KEY=${NCLOUD_SECRET_KEY}
      - NCLOUD_BUCKET_NAME=${NCLOUD_BUCKET_NAME}

networks:
  camon:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16