version: "3.9"

services:
  api:
    container_name: api-camon
    image: ${NCLOUD_REGISTRY_URL}/api-camon
    networks:
      - camon
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env

  media:
    container_name: media-camon
    image: ${NCLOUD_REGISTRY_URL}/media-camon
    networks:
      - camon
    ports:
      - "3001:3001"
      - "30000-31000:30000-31000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_MEDIA=${REDIS_MEDIA}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_SERVER_URL=${API_SERVER_URL}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT}
      - RECORD_SERVER_URL=${RECORD_SERVER_URL}
      - SERVER_PRIVATE_IP=${SERVER_PRIVATE_IP}
      - PUBLIC_RECORD_SERVER_URL=${PUBLIC_RECORD_SERVER_URL}


  chat:
    container_name: chat-camon
    image: ${NCLOUD_REGISTRY_URL}/chat-camon
    networks:
      - camon
    expose:
      - "3002"
    ports:
      - "3002:3002"

  record:
    container_name: record-camon
    image: ${NCLOUD_REGISTRY_URL}/record-camon
    networks:
      - camon
    ports:
      - "3003:3003"
    environment:
      - NCLOUD_ACCESS_KEY=${NCLOUD_ACCESS_KEY}
      - NCLOUD_SECRET_KEY=${NCLOUD_SECRET_KEY}
      - NCLOUD_BUCKET_NAME=${NCLOUD_BUCKET_NAME}

networks:
  camon:
    driver: bridge