name: Front Ci/Cd
on:
  push:
    branches:
      - develop
    paths:
      - 'apps/client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # GitHub 레포지토리 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # pnpm 설치
      - name: Install pnpm
        run: npm install -g pnpm

      # 의존성 설치
      - name: Install dependencies
        working-directory: apps/client
        run: pnpm install --no-frozen-lockfile

      # 빌드 실행
      - name: Build front-end
        working-directory: apps/client
        run: pnpm build

      - name: Verify build output
        run: ls -la apps/client/dist

      - name: Upload files to server using SCP
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_SERVER_KEY }}" | ssh-add -
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /home/ubuntu/myapp"
          scp -o StrictHostKeyChecking=no -r apps/client/dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/myapp
          ssh-agent -k

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          script: |
            sudo mkdir -p /var/www/myapp
            sudo chown -R www-data:www-data /var/www/myapp
            sudo cp -r /home/ubuntu/myapp/. /var/www/myapp
            sudo rm -rf /home/ubuntu/myapp
          
      
