name: Media Server CI/CD
on:
  push:
    branches:
      - develop
      - Fix/221
    paths:
      - 'apps/media/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: media-camon
      MEDIA_PORT: 3001
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_MEDIA: ${{ secrets.REDIS_MEDIA }}
      ANNOUNCED_IP: ${{ secrets.ANNOUNCED_IP }}
      API_SERVER_URL: ${{ secrets.API_SERVER_URL }}
      HTTP_TIMEOUT: ${{ secrets.HTTP_TIMEOUT }}
      RECORD_SERVER_URL: ${{ secrets.RECORD_SERVER_URL }}
      SERVER_PRIVATE_IP: ${{ secrets.SERVER_PRIVATE_IP }}
      PUBLIC_RECORD_SERVER_URL: ${{ secrets.PUBLIC_RECORD_SERVER_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Ncloud Container Registry
        env:
          USERNAME: ${{ secrets.NCLOUD_ACCESS_KEY }}
          PASSWORD: ${{ secrets.NCLOUD_SECRET_KEY }}
          REGISTRY_URL: ${{ secrets.NCLOUD_REGISTRY_URL }}
        run: |
          echo "$PASSWORD" | docker login -u "$USERNAME" "$REGISTRY_URL" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
          --cache-from=${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest \
          -f ./apps/media/Dockerfile \
          -t ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest \
          --build-arg MEDIA_PORT=$MEDIA_PORT \
          --build-arg REDIS_HOST=$REDIS_HOST \
          --build-arg REDIS_PORT=$REDIS_PORT \
          --build-arg REDIS_MEDIA=$REDIS_MEDIA \
          --build-arg ANNOUNCED_IP=$ANNOUNCED_IP \
          --build-arg API_SERVER_URL=$API_SERVER_URL \
          --build-arg HTTP_TIMEOUT=$HTTP_TIMEOUT \
          --build-arg RECORD_SERVER_URL=$RECORD_SERVER_URL \
          --build-arg SERVER_PRIVATE_IP=$SERVER_PRIVATE_IP \
          --build-arg PUBLIC_RECORD_SERVER_URL=$PUBLIC_RECORD_SERVER_URL \
          .         

      - name: Push to Ncloud Container Registry
        run: |
          docker push ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest

  deploy-and-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo lsof -i :3001
            sudo lsof -i :30000-31000
            sudo docker login -u ${{secrets.NCLOUD_ACCESS_KEY}} -p ${{ secrets.NCLOUD_SECRET_KEY }} ${{ secrets.NCLOUD_REGISTRY_URL }}
            sudo docker stop media-camon || true
            sudo docker rm media-camon || true
            sudo docker rmi ${{ secrets.NCLOUD_REGISTRY_URL }}/media-camon:latest || true
            sudo docker pull ${{ secrets.NCLOUD_REGISTRY_URL }}/media-camon:latest
            sudo docker run -d --name media-camon \
              -p 3001:3001 \
              -p 30000-31000:30000-31000 \
              --network=bridge \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
              -e REDIS_MEDIA=${{ secrets.REDIS_MEDIA }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e API_SERVER_URL=${{ secrets.API_SERVER_URL }} \
              -e HTTP_TIMEOUT=${{ secrets.HTTP_TIMEOUT }} \
              -e RECORD_SERVER_URL=${{ secrets.RECORD_SERVER_URL }} \
              -e SERVER_PRIVATE_IP=${{ secrets.SERVER_PRIVATE_IP }} \
              -e PUBLIC_RECORD_SERVER_URL=${{ secrets.PUBLIC_RECORD_SERVER_URL }} \
              ${{ secrets.NCLOUD_REGISTRY_URL }}/media-camon:latest
            sudo docker image prune -f

      - name: Check container status
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            sudo docker ps -f name=media-camon
            sudo docker exec media-camon env | grep REDIS
            sudo docker logs media-camon