name: Record Server Ci/Cd
on:
  push:
    branches:
      - develop
    paths:
      - 'apps/record/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: record-camon
      RECORD_PORT: ${{ secrets.RECORD_PORT }}
      NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
      NCLOUD_SECRET_KEY=: ${{ secrets.NCLOUD_SECRET_KEY }}
      NCLOUD_BUCKET_NAME=: ${{ secrets.NCLOUD_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Ncloud Container Registry
        env:
          USERNAME: ${{ secrets.NCLOUD_ACCESS_KEY }}
          PASSWORD: ${{ secrets.NCLOUD_SECRET_KEY }}
          REGISTRY_URL: ${{ secrets.NCLOUD_REGISTRY_URL }}
        run: |
          echo "$PASSWORD" | docker login -u "$USERNAME" "$REGISTRY_URL" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f ./apps/record/Dockerfile -t ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest \
            --build-arg RECORD_PORT=$RECORD_PORT \
            --build-arg NCLOUD_ACCESS_KEY=$NCLOUD_ACCESS_KEY \
            --build-arg NCLOUD_SECRET_KEY=$NCLOUD_ACCESS_KEY \
            --build-arg NCLOUD_BUCKET_NAME=$NCLOUD_BUCKET_NAME \
            .

      - name: Push to Ncloud Container Registry
        run: |
          docker push ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest
      
  deploy-and-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout for docker-compose
        uses: actions/checkout@v2

      - name: Copy docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SERVER_USER }}/camon"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          envs: RECORD_PORT,NCLOUD_ACCESS_KEY,NCLOUD_SECRET_KEY,NCLOUD_BUCKET_NAME
          script: |
            cd /home/${{ secrets.SERVER_USER }}/camon
            sudo docker login -u ${{secrets.NCLOUD_ACCESS_KEY}} -p ${{ secrets.NCLOUD_SECRET_KEY }} ${{ secrets.NCLOUD_REGISTRY_URL }}

            sudo docker stop record-camon || true
            sudo docker rm record-camon || true
            sudo docker rmi ${{ secrets.NCLOUD_REGISTRY_URL }}/record-camon:latest || true

            sudo docker pull ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest
            sudo docker-compose up -d record
            sudo docker image prune -f

      - name: Check container status
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/camon
            sudo docker-compose ps record
            sudo docker-compose logs --tail=100 record