name: Record Server Ci/Cd
on:
  push:
    branches:
      - develop
      - Fix/347
    paths:
      - 'apps/record/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: record-camon
      RECORD_PORT: ${{ secrets.RECORD_PORT }}
      NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
      NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
      NCLOUD_BUCKET_NAME: ${{ secrets.NCLOUD_BUCKET_NAME }}
      API_SERVER_URL: ${{ secrets.API_SERVER_URL }}
      CDN_URL: ${{ secrets.CDN_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Ncloud Container Registry
        env:
          USERNAME: ${{ secrets.NCLOUD_ACCESS_KEY }}
          PASSWORD: ${{ secrets.NCLOUD_SECRET_KEY }}
          REGISTRY_URL: ${{ secrets.NCLOUD_REGISTRY_URL }}
        run: |
          echo "$PASSWORD" | docker login -u "$USERNAME" "$REGISTRY_URL" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f ./apps/record/Dockerfile -t ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest \
            --build-arg RECORD_PORT=$RECORD_PORT \
            --build-arg NCLOUD_ACCESS_KEY=$NCLOUD_ACCESS_KEY \
            --build-arg NCLOUD_SECRET_KEY=$NCLOUD_SECRET_KEY \
            --build-arg NCLOUD_BUCKET_NAME=$NCLOUD_BUCKET_NAME \
            --build-arg API_SERVER_URL=$API_SERVER_URL \
            --build-arg CDN_URL=$CDN_URL \
            .

      - name: Push to Ncloud Container Registry
        run: |
          docker push ${{ secrets.NCLOUD_REGISTRY_URL }}/$IMAGE_NAME:latest
      
  deploy-and-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      IMAGE_NAME: record-camon
      RECORD_PORT: ${{ secrets.RECORD_PORT }}
      NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
      NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
      NCLOUD_BUCKET_NAME: ${{ secrets.NCLOUD_BUCKET_NAME }}
      NCLOUD_REGISTRY_URL: ${{ secrets.NCLOUD_REGISTRY_URL }}
      API_SERVER_URL: ${{ secrets.API_SERVER_URL }}
      CDN_URL: ${{ secrets.CDN_URL }}

    steps:
      - name: Checkout for docker-compose
        uses: actions/checkout@v2

      - name: Copy docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SERVER_USER }}/camon"

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          envs: RECORD_PORT,NCLOUD_ACCESS_KEY,NCLOUD_SECRET_KEY,NCLOUD_BUCKET_NAME,NCLOUD_REGISTRY_URL,API_SERVER_URL,CDN_URL
          script: |
            cd /home/${{ secrets.SERVER_USER }}/camon
            
            echo "RECORD_PORT=$RECORD_PORT" > .env
            echo "NCLOUD_ACCESS_KEY=$NCLOUD_ACCESS_KEY" >> .env
            echo "NCLOUD_SECRET_KEY=$NCLOUD_SECRET_KEY" >> .env
            echo "NCLOUD_BUCKET_NAME=$NCLOUD_BUCKET_NAME" >> .env
            echo "NCLOUD_REGISTRY_URL=$NCLOUD_REGISTRY_URL" >> .env
            echo "API_SERVER_URL=$API_SERVER_URL" >> .env
            echo "CDN_URL=$CDN_URL" >> .env
            
            sudo docker login -u $NCLOUD_ACCESS_KEY -p $NCLOUD_SECRET_KEY $NCLOUD_REGISTRY_URL

            sudo docker stop record-camon || true
            sudo docker rm record-camon || true
            sudo docker rmi $NCLOUD_REGISTRY_URL/record-camon:latest || true
      
            sudo docker pull $NCLOUD_REGISTRY_URL/record-camon:latest
            sudo docker tag $NCLOUD_REGISTRY_URL/record-camon:latest record-camon
      
            sudo docker-compose up -d record
      
            sudo docker image prune -f
      - name: Check container status
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/camon
            sudo docker-compose ps record
            sudo docker-compose logs --tail=100 record